FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY shared/ ./shared/
ENV FLASK_APP=api.server

ENV PYTHONUNBUFFERED=1
ENV API_PORT=8080

CMD ["python", "-m", "api.server"]
